### ISSUE TITLE
React.js

### ISSUE THREAD

**Issue by makenai** [vegasjs/Meetings#14]

**Comment by shakefon** [comment]
Haven't asked him but Chase gave me an intro to React that convinced me of its usefulness. Might be worth asking if he would like to give a talk on it?

**Comment by joemcbride** [comment]
I will volunteer to present this in May, unless Chase has volunteered already.

**Comment by slooker** [comment]
I'd love to see this presented too.  I've not really understood what it's usefulness is in going through the tutorial.

**Comment by makenai** [comment]
@joemcbride Any chance you'd like to give this talk at the next meetup on the 15th?

**Comment by joemcbride** [comment]
@makenai Yes I can.  How long are the talks typically?  1hr?

**Comment by makenai** [comment]
Up to 35 minutes including any Q&A time you'd like to use.

**Comment by makenai** [comment]
Also, I just realized I have it on the wrong day - they are supposed to be on Tuesdays, so it will be the 16th. Let me know if you can do a 35 minutes-ish talk on the 16th and I'll get it on the schedule and fix all the dates.

Thanks!

**Comment by joemcbride** [comment]
Yep that works.

**Comment by makenai** [comment]
Thanks Joe! I've updated the site with info and have another talk coming from Zach K. Do you have a specific title you'd like me to use?

**Comment by joemcbride** [comment]
Title you have looks great.  :+1:

**Comment by zpnk** [comment]
Joe's slides: http://www.slideshare.net/joetmcbride/react-fundamentals
