### ISSUE TITLE
Js Inheritance talk request

### ISSUE THREAD

**Issue by aronysidoro** [vegasjs/Meetings#18]
I want to request a talk on Javascript inheritance.  If there are different strategies, like `composition`, and if Javascript has something similar to `super` in Python for overwriting, and changing different `Object` properties at initialization.  

Thanks

**Comment by makenai** [comment]
Great idea! I'm currently looking for a speaker for this. Will add it to the next meetup if I have luck.

**Comment by zpnk** [comment]
Pawel's slides: http://www.slideshare.net/makenai1/java-script-inheritence
