### ISSUE TITLE
LeafletJS

### ISSUE THREAD

**Issue by makenai** [vegasjs/Meetings#27]
A JavaScript tile based mapping API.

To be given by Ryan

**Comment by ryanjhodge** [comment]
Hey @makenai, so that conference fell through and I will definitely be able to make the July Meetup.

**Comment by makenai** [comment]
Great, thank you!

**Comment by zpnk** [comment]
Ryan's presentation: http://github.com/ryanjhodge/vegasjs-web-mapping
