### ISSUE TITLE
Hot new ES6 Stuff

### ISSUE THREAD

**Issue by makenai** [vegasjs/Meetings#3]
Requested by Dan (down with coffeescript)

**Comment by makenai** [comment]
Given by Pawel

**Comment by shakefon** [comment]
You  may enjoy this resource while preparing your talk, if you've not already seen it :)

https://github.com/ericdouglas/ES6-Learning

**Comment by makenai** [comment]
Thanks @shakefon! This will come in handy.

**Comment by zpnk** [comment]
Link to Pawel's slides: http://www.slideshare.net/makenai1/new-es6-hotness
