### ISSUE TITLE
JavaScript Easter Eggs with the Konami code

### ISSUE THREAD

**Issue by jenwilhelm** [vegasjs/Meetings#32]
Learn how to add an easter egg to your site that's triggered by typing the konami code.

**Comment by jenwilhelm** [comment]
Also, I can give this talk.

**Comment by makenai** [comment]
⬆️⬆️⬇️⬇️⬅️➡️⬅️➡️BA

**Comment by zpnk** [comment]
This is an awesome talk idea! Can't wait to hear about it.

@makenai @jenwilhelm I feel like there is a certain website that is lacking this amazing feature!

**Comment by jenwilhelm** [comment]
@zpnk Think again! :D Although you will need to be logged in to see.

**Comment by zpnk** [comment]
@jenwilhelm I was thinking something something dinosaurs but that was far better than I could have ever imagined. :clap:

**Comment by jenwilhelm** [comment]
@zpnk Glad you like! Would liked to have put it on the homepage, but couldn't justify including jQuery + additional stylesheets for something that 99% of people won't see. :unamused:

**Comment by zpnk** [comment]
To be given by Jen on December 15!
