### ISSUE TITLE
That's So Meta: A talk on how to give talks

### ISSUE THREAD

**Issue by chaseadamsio** [vegasjs/Meetings#38]
Most people are afraid to give present a topic at a meetup or a conference, but with the right preparation, guidance and a little magic, it can be a really fun and NOT so super stressful experience!

In this talk I'd like to cover:
- Preparation / Organization
- Tips the presentation itself
- Things I've found helpful
- Things I've learned by doing them wrong

**Comment by zpnk** [comment]
[Tentative] for December 15!

**Comment by makenai** [comment]
@chaseadamsio I mentioned this would be a good talk for next meetup. Do you think you can do Dec 15?

**Comment by chaseadamsio** [comment]
I'm going to be out of town for almost the whole month of December, how about January?

**Comment by makenai** [comment]
Sounds good - enjoy the holidays, Chase!

**Comment by chaseadamsio** [comment]
:+1: super excited to give this talk!
