### ISSUE TITLE
Dave Stevens  Presents : Truly Universal Javascript

### ISSUE THREAD

**Issue by makenai** [vegasjs/Meetings#43]
to be pressured by Jimmy Jacobson

**Comment by chaseadamsio** [comment]
:+1:

**Comment by makenai** [comment]
@shakefon Thanks! Can I bug you for a few sentences describing the talk?

**Comment by chaseadamsio** [comment]
Truly universal.

**Comment by shakefon** [comment]
Isomorphic JavaScript. Universal JavaScript. Whatever you've heard it called, you're probably intrigued, or maybe confused. Let me show you why the ability to share JavaScript between your client-side, server-side, and other parts of your app makes today an exciting time to be alive. #reactjs

**Comment by zpnk** [comment]
Given by Dave!
