### ISSUE TITLE
Introduction to TypeScript

### ISSUE THREAD

**Issue by zpnk** [vegasjs/Meetings#47]
How does it work? Why should I use it?

**Comment by zpnk** [comment]
To be given by Matt.

**Comment by makenai** [comment]
Hey @mattmutt, are you still able to give this talk next week? Thanks!

**Comment by mattmutt** [comment]
Yep, entitled "TypeScript: Make JS Great Again" or something funny along those lines

**Comment by makenai** [comment]
@mattmutt Cool! Sorry, I sent out an announcement with a TBD (had some trouble getting in touch via Meetup) but I'll send out an addendum tomorrow. Having the update go out as an additional reminder should be good for turnout in any case. :)

**Comment by mattmutt** [comment]
So the meetup server might be dropping messages, I did reply to your inquiry last week.  To make the talk interesting for all levels, I'll keep it basic, but are there people in the group who want more out of it? I can dive into more advanced topics and benefits.

**Comment by zpnk** [comment]
@mattmutt I'd like to know more about advanced use cases and benefits of TS!

**Comment by makenai** [comment]
Here's what I added for the description:

TypeScript is a version of JavaScript which adds optional static typing, classes and interfaces among other things. Some might say it puts the Java back into JavaScript. Find out why this might be something you want to do, and how you can get started!

**Comment by mattmutt** [comment]
straight forward.  I just gave a preacher style sermon on TS last night to a team , who was less than thrilled about learning this "new language". Some people are just scared of anything that disrupts their normal work!
