### ISSUE TITLE
Node Interactive Recap

### ISSUE THREAD

**Issue by jimmyjacobson** [vegasjs/Meetings#49]
Adam Englander, Python, PHP and Javascript Developer at LaunchKey, attended NodeConf in December 2015. In this talk he will be providing VegasJS with a round up of the talks he heard and the awesome stuff he saw.

**Comment by makenai** [comment]
Can you please provide a title, short description and difficulty level?

**Comment by jimmyjacobson** [comment]
@makenai updated
