### ISSUE TITLE
Intro to Google Apps Script 

### ISSUE THREAD

**Issue by zipzit** [vegasjs/Meetings#50]
Google provides a JavaScript platform that runs via cloud server, with access to a huge library of functions that tie into Calendar, Docs, Drive, Gmail, Forms, Maps, Drawings and (Spread)Sheets.  This collection of tools / api is known as "Google Apps Script".

Is there any interest in learning more about Google Apps Script via tutorial / usage case?

Update:  The Execution API allows developers to execute scripts from any client (browser, server, mobile, or any device). You provide the authorization, and the Execution API will run your script. (API released 9/2015)

I'm happy to volunteer to make a presentation.  --LB Corney
I think the other volunteer is Andrew Bauman

**Comment by jimmyjacobson** [comment]
Thank you @lb_conrey

**Comment by zipzit** [comment]
Here's [the link](http://dogfeatherdesign.com/js-google-apps-script-presentation-21-june-2016/) to my presentation.
