### ISSUE TITLE
Algorithms: Problem solving strategies and being fearless... in Javascript

### ISSUE THREAD

**Issue by makenai** [vegasjs/Meetings#53]
By @debugish 

Please comment if you would like to hear about something in particular, to contribute or to be kewl.

**Comment by debugish** [comment]
Title: Algorithms: Problem solving strategies and being fearless... in Javascript

Description:
We'll solve a couple of difficult problems algorithmically. No pre-baked or googled solutions, but with a couple of guiding principles, elbow-grease and a can-do attitude!
