### ISSUE TITLE
Hosting a Node.JS server without spending a lot of $$

### ISSUE THREAD

**Issue by zipzit** [vegasjs/Meetings#61]
Review of inexpensive (er... free) server hostings that are available to test out your code, learn new skills. (Development and Prototyping) 

Server
- OpenShift (3 small gears, 512MB Ram/gear, 1Gb storage/gear, idle after 24 hours)
- Heroku (512MB Ram, 1 web & 1 worker.  Sleeps after 30 minutes of inactivity, must sleep 6 hrs in 24.0
- Cloudwith.me (1Gb memory, 1 2.5Ghz CPU, Amazon EC2 Instance) (Need to verify this one.. sounds too good to be true...)

AWS Lambda
- 1,000,000 free requests per month**
- Up to 3.2 million seconds of compute time per month**

Data Storage
- OpenShift (you can install MySQL, PostgreSQL, MongoDB, and SQLite within your gears..)
- mlab.com (MongoDB 500Mb)
- Heroku Postgres 10K rows of storage = free.
- Heroku Redis (25 MB, 20 CONNECTIONS)
- Amazon DynamoDB (25Gb)

Note there are a whole lot of free offers that are time limited (Most notably AWS, e.g. 12 months free, then $$)  The items listed above are free tier offers do not automatically expire at the end of a trial period, but are available to both existing and new customers indefinitely.  I guess you could provide new email addresses to continue extending the offers, but where's the fun in that?

**Comment by zpnk** [comment]
[zeit.co/now](https://zeit.co/now) :)
