### ISSUE TITLE
nodeschool.io

### ISSUE THREAD

**Issue by noopkat** [vegasjs/Meetings#9]
length = 5 min || 20 min

+ intro to what it is, what it offers
+ a primer on what you should know before you start a workshopper
  + how to get around the terminal
  + best practices for smoothing the experience over
  + best resources for supplementary teachings if you are more a visual learner as well.

**Comment by makenai** [comment]
Thanks Suz!

**Comment by zpnk** [comment]
Suz's slides: http://www.slideshare.net/noopkat/nodeschool
